### ISSUE TITLE
Api scorito

### ISSUE THREAD

**Issue by Daanhiemstra** [jvdlaar/scorito#1]
Hi Johnny,

Interessant leuk hobby project! Ik wilde iets vergelijkbaars doen voor het topcoach spel; alleen hoe kom je aan deze api keys als ik vragen mag?

groeten,

daan

**Comment by jvdlaar** [comment]
Ik heb in de browser gewoon in mijn netwerk tab gekeken. Alle apis waren openbaar (behalve als je dingen wilt opslaan).

**Comment by Daanhiemstra** [comment]
Bedankt! Het is gelukt!

Op wo 22 dec. 2021 om 16:26 schreef Johnny van de Laar <
***@***.***>
